FROM jenkins/jenkins:lts

USER root

# Install Docker and Docker Compose
RUN curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh \
    && curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose \
    && ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

USER jenkins
