version: "3.8"

services:
  web:
    build: .
    container_name: static_nginx_site
    ports:
      - "3000:80"
    volumes:
      - .:/usr/share/nginx/html
    restart: always

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins  # Reference the custom Jenkins Dockerfile
    container_name: devops_jenkins
    ports:
      - "9000:8080"   # host:container
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

volumes:
  jenkins_home:
